package config

// Default returns the P0 baseline configuration without replacing legacy paths.
// These values match the existing CLI defaults so introducing config does not
// change runtime behavior before the processor split is complete.
func Default() Config {
	return Config{
		General: GeneralConfig{
			DefaultOutputFormat: "report",
			TimeZone:            "CST",
		},
		Iostat: IostatConfig{
			Enabled:                true,
			QueueHard:              1.0,
			QueueSoft:              0.3,
			CPUWaitHardPct:         20,
			CPUWaitSoftPct:         10,
			LatencyIOPSSoft:        10,
			UtilHardPct:            95,
			UtilSoftPct:            80,
			UtilMinSamples:         3,
			NVMeLatencyHardMS:      8,
			NVMeLatencySoftMS:      6,
			DefaultLatencyHardMS:   50,
			DefaultLatencySoftMS:   37.5,
			LatencyZScoreThreshold: 3,
			LatencyMADThreshold:    3,
			LatencyIQRMultiplier:   1.5,
		},
		Meminfo: MeminfoConfig{
			Enabled:                     true,
			AvailableWarnPct:            20,
			AvailableSoftPct:            30,
			AvailableSeverePct:          10,
			AvailableSevereMB:           8192,
			AvailableWarnMB:             16384,
			AnonLeakHardMB:              200,
			AnonLeakSoftMB:              128,
			AnonLeakDeltaMB:             200,
			AnonLeakHardRateMBPerSample: 50,
			AnonLeakSoftRateMBPerSample: 20,
			AnonSampleSeconds:           5,
			AnonLeakHardPct:             5,
			AnonLeakSoftPct:             1,
			SwapWarnPct:                 10,
			SwapSeverePct:               10,
			SwapGrowthSoftMB:            128,
			SwapBurstPct:                20,
			CommitWarnPct:               90,
			CommitHardPct:               100,
			SlabWarnMB:                  20480,
			SlabSoftMB:                  10240,
			SlabWarnPct:                 8,
			SlabSoftPct:                 4,
			UnreclaimWarnPct:            2,
			UnreclaimSoftPct:            1,
			DirtySoftPct:                2,
			DirtyHardPct:                5,
			WritebackSoftPct:            0.2,
			WritebackHardPct:            1.0,
			WritebackSoftMB:             256,
			WritebackHardMB:             1024,
			AnonWindowPoints:            36,
			ShortWindowPoints:           36,
			LongWindowPoints:            720,
			SlopeBurstMBPerSample:       500,
			SlabSlopeBurstMBPerSample:   200,
			KernelAbsWarnMB:             500,
			KernelDeltaPctWarn:          50,
			VPatternDropMB:              4096,
			VPatternRecoverMB:           2048,
			SuddenChangePct:             2,
			SuddenChangeMinMB:           2048,
		},
		Top: TopConfig{
			Enabled:              true,
			CPUIdleHardPct:       10,
			CPUIdleSoftPct:       20,
			CPUWaitHardPct:       20,
			CPUWaitSoftPct:       10,
			CPUStealHardPct:      10,
			CPUStealSoftPct:      5,
			LoadHighSoft:         4,
			LoadHighHard:         8,
			LoadPerCPUSoft:       0.70,
			LoadPerCPUHard:       1.00,
			RunnablePerCPU:       0.70,
			RunnableSoft:         8,
			CPUIdleHighPct:       80,
			HighCPUProcessPct:    50,
			HighMemoryProcessPct: 5,
		},
		AI: AIConfig{
			Enabled:             false,
			DefaultOutputFormat: "ml",
			TimeoutSeconds:      0,
		},
	}
}
